spring.application.name=GitHubApiServer

external.api.server.url=api.github.com
external.api.server.scheme=https
external.api.server.port=443
external.api.server.userpath=/users
external.api.server.repospath=/repos
external.api.server.branchespath=/branches